import fs from 'fs';
const s = fs.readFileSync(process.env.TEMP + '/locator-39.js', 'utf8');
const marker = s.indexOf('SET_EXCESSIVE_IDLING_REPORT');
const start = s.lastIndexOf(':function(A,a,i)', marker);
const next = s.indexOf(':function(', marker + 50);
const chunk = s.slice(start, next > 0 ? next : start + 200000);
console.log('chunk len', chunk.length);
const re = /["'`]([^"'`]{0,80}(?:[Ii]dl|[Ee]xcess|report)[^"'`]{0,80})["'`]/g;
const set = new Set();
let m;
while ((m = re.exec(chunk))) set.add(m[1]);
console.log([...set].slice(0, 100).join('\n'));
